services:
  web: &web
    build: .
    image: web
    ports:
      - "5000:5000"
    command: bash -c "python manage.py runserver 0.0.0.0:5000"
    environment:
      - CELERY_BROKER_URL=redis://redis_server:6380/0
      - DOCKER_USE=True
    depends_on:
      - redis_server
  celery_worker_email:
    <<: *web
    image: celery_worker_email
    command: celery -A core.celery worker --loglevel=info -Q email-queue
    ports: []
    depends_on:
      - redis_server
  celery_worker_general:
    <<: *web
    image: celery_worker_general
    command: celery -A core.celery worker --loglevel=info -Q general-queue
    ports: []
    depends_on:
      - redis_server
  celery_worker_helper:
    <<: *web
    image: celery_worker_helper
    command: celery -A core.celery worker --loglevel=info -Q helper-queue
    ports: []
    depends_on:
      - redis_server
  redis_server:
    image: redis:alpine
    command: --port 6380
    ports:
      - "6380:6380"